---
inherit_from: .rubocop_todo.yml

inherit_gem:
  voxpupuli-rubocop: rubocop.yml

Naming/FileName:
  Description: Some files violates the snake_case convention
  Exclude:
    - 'lib/beaker-docker.rb'

AllCops:
  TargetRubyVersion: 3.2
